include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - build/**
    - lib/generated/intl/**
    - lib/generated/l10n.dart

linter:
  rules:
    prefer_single_quotes: true
    avoid_classes_with_only_static_members: false
    sort_pub_dependencies: false